### ISSUE TITLE
进度如何？

### ISSUE THREAD

**Issue by hack2012** [NS-Sp4ce/AWVS12-Chinese-Translate#1]
兄弟，AWVS11的汉化包已经不适用于12了，12的汉化进度如何呀？

**Comment by NS-Sp4ce** [comment]
存有汉化文件的硬盘在一次宕机中挂了……后面一直忘了这事了。。。忙完这一阵子会重启进度的

**Comment by hack2012** [comment]
期待兄弟的汉化，多谢。

**Comment by NS-Sp4ce** [comment]
> 期待兄弟的汉化，多谢。

我尽快 哈哈
